### ISSUE TITLE
PackageIdentifier is missing a proper option management on start

### ISSUE THREAD

**Issue by ericbl** [siemens/continuous-clearing#24]
running the  PackageIdentifier.exe without any option throws an exception: 

`Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: Invalid folder path -/mnt/Input
   at LCT.Common.FolderAction.ValidateFolderPath(String folderPath) in C:\Users\z0045k0r\source\repos\continuous-clearing\src\LCT.Common\FolderAction.cs:line 75
   at LCT.Common.CommonAppSettings.set_PackageFilePath(String value) in C:\Users\z0045k0r\source\repos\continuous-clearing\src\LCT.Common\CommonAppSettings.cs:line 123`

consider a proper list of options to be set for the program to run gently.

**Comment by karthika-g** [comment]
According to the current workflow of the tool it is mandatory to give at least one argument while running the exe. Which is why you are getting the above issue. More details of the arguments and how to run is available in the usage document.

Question : Are you suggesting more like a list of options to be provided(CLI help options) rather than the exception given in the image in the cli?

**Comment by karthika-g** [comment]
Feature added in V 3.1.0 and released
